// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list_my_orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's recent orders at Nosty's Fresh Fast Food.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many recent orders to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select(
      "id, order_number, status, order_type, total_amount, delivery_fee, tip_amount, payment_method, payment_confirmed, delivery_address, notes, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_order_default = defineTool2({
  name: "get_my_order",
  title: "Get one of my orders",
  description: "Get full details (items + totals) for one of the signed-in user's orders, by order number.",
  inputSchema: {
    order_number: z2.number().int().positive().describe("The Nosty's order number, e.g. 1234.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: order, error } = await supabase.from("orders").select(
      "id, order_number, status, order_type, total_amount, delivery_fee, tip_amount, payment_method, payment_confirmed, delivery_address, notes, created_at, delivered_at"
    ).eq("user_id", ctx.getUserId()).eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) return { content: [{ type: "text", text: "Order not found" }], isError: true };
    const { data: items, error: itemsErr } = await supabase.from("order_items").select("item_name, quantity, price").eq("order_id", order.id);
    if (itemsErr) return { content: [{ type: "text", text: itemsErr.message }], isError: true };
    const payload = { ...order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_menu.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_menu_default = defineTool3({
  name: "list_menu",
  title: "List Nosty's menu",
  description: "List Nosty's Fresh Fast Food menu items (name, category, price, availability). Optional category filter.",
  inputSchema: {
    category: z3.string().trim().min(1).optional().describe("Optional category name to filter by."),
    only_available: z3.boolean().default(true).describe("If true, hide unavailable items.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, only_available }, ctx) => {
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("menu_items").select("id, name, description, category, price, is_available, image_url").order("category", { ascending: true }).order("name", { ascending: true });
    if (category) q = q.ilike("category", `%${category}%`);
    if (only_available ?? true) q = q.eq("is_available", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Nosty's user id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aweceghpsgqhilydnoun";
var mcp_default = defineMcp({
  name: "nostys-mcp",
  title: "Nosty's Fresh Fast Food",
  version: "0.1.0",
  instructions: "Tools for Nosty's Fresh Fast Food customers. Use `whoami` to check the signed-in user, `list_menu` to browse Nosty's menu, `list_my_orders` for the user's recent orders, and `get_my_order` for full order details by order number.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_menu_default, list_my_orders_default, get_my_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
